name: Build the project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build the code
        run: |
          sudo apt install -y build-essential python-is-python3
          make
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests.py